# Generated by Django 4.1.9 on 2023-05-18 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "last_change",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="Last Change"
                    ),
                ),
                (
                    "create_date",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="Create Date"
                    ),
                ),
                (
                    "delete_datetime",
                    django_jalali.db.models.jDateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="Delete Datetime",
                    ),
                ),
                ("item", models.JSONField()),
                (
                    "shipping_price",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DiscountCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "last_change",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="Last Change"
                    ),
                ),
                (
                    "create_date",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="Create Date"
                    ),
                ),
                (
                    "delete_datetime",
                    django_jalali.db.models.jDateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="Delete Datetime",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "last_change",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="Last Change"
                    ),
                ),
                (
                    "create_date",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="Create Date"
                    ),
                ),
                (
                    "delete_datetime",
                    django_jalali.db.models.jDateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="Delete Datetime",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("r", "registered"),
                            ("p", "processing"),
                            ("s", "sent"),
                            ("d", "delivered"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.cart"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
