# Generated by Django 4.1.9 on 2023-05-18 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcoupon",
            name="discount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.discount"
            ),
        ),
    ]
