# Generated by Django 4.1.9 on 2023-05-18 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="item",
            field=models.JSONField(verbose_name="Item in cart"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="shipping_price",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Shipping Price",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("r", "registered"),
                    ("p", "processing"),
                    ("s", "sent"),
                    ("d", "delivered"),
                ],
                max_length=1,
                verbose_name="Status",
            ),
        ),
    ]
