# Generated by Django 4.1.9 on 2023-05-18 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "last_change",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="Last Change"
                    ),
                ),
                (
                    "create_date",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="Create Date"
                    ),
                ),
                (
                    "delete_datetime",
                    django_jalali.db.models.jDateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="Delete Datetime",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Category Is Active"
                    ),
                ),
                (
                    "discount_activate_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, null=True, verbose_name="Activate at"
                    ),
                ),
                (
                    "discount_deactivate_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, null=True, verbose_name="Deactivate at"
                    ),
                ),
                (
                    "discount_is_active",
                    models.BooleanField(default=False, verbose_name="Active discount"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "last_change",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="Last Change"
                    ),
                ),
                (
                    "create_date",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="Create Date"
                    ),
                ),
                (
                    "delete_datetime",
                    django_jalali.db.models.jDateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="Delete Datetime",
                    ),
                ),
                (
                    "amount_of_percentage_discount",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(80)]
                    ),
                ),
                ("amount_of_non_percentage_discount", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InformationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "last_change",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="Last Change"
                    ),
                ),
                (
                    "create_date",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="Create Date"
                    ),
                ),
                (
                    "delete_datetime",
                    django_jalali.db.models.jDateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="Delete Datetime",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "last_change",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="Last Change"
                    ),
                ),
                (
                    "create_date",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="Create Date"
                    ),
                ),
                (
                    "delete_datetime",
                    django_jalali.db.models.jDateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="Delete Datetime",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                (
                    "count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("product_info", models.JSONField()),
                (
                    "price",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "discount_activate_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, null=True, verbose_name="Activate at"
                    ),
                ),
                (
                    "discount_deactivate_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, null=True, verbose_name="Deactivate at"
                    ),
                ),
                (
                    "discount_is_active",
                    models.BooleanField(default=False, verbose_name="Active discount"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "last_change",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="Last Change"
                    ),
                ),
                (
                    "create_date",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="Create Date"
                    ),
                ),
                (
                    "delete_datetime",
                    django_jalali.db.models.jDateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="Delete Datetime",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Comment Approved"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "last_change",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="Last Change"
                    ),
                ),
                (
                    "create_date",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="Create Date"
                    ),
                ),
                (
                    "delete_datetime",
                    django_jalali.db.models.jDateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="Delete Datetime",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/product_images")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
